<a href="https://colab.research.google.com/github/Surajit-Debnath/nn-from-scratch/blob/master/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
BASE_PATH = "/content/drive/MyDrive/AWS ML CHALLANGE/"

TRAIN_PATH = f"{BASE_PATH}dataset/train"
TEST_PATH = f"{BASE_PATH}dataset/test"

In [9]:
import os

print(os.listdir(BASE_PATH))
print(os.listdir(TRAIN_PATH))
print(os.listdir(TEST_PATH))

['dataset', 'models', 'output', 'intermediate', 'submission', 'notebooks']
['train_source2.tsv', 'train_source3.tsv', 'train_source1.tsv', 'train_ground_truth.tsv']
['test_source1.tsv', 'test_source2.tsv', 'test_source3.tsv']

In [10]:
import pandas as pd

s1 = pd.read_csv(
    f"{TRAIN_PATH}/train_source1.tsv",
    sep="\t"
)

s2 = pd.read_csv(
    f"{TRAIN_PATH}/train_source2.tsv",
    sep="\t"
)

s3 = pd.read_csv(
    f"{TRAIN_PATH}/train_source3.tsv",
    sep="\t"
)

ground_truth = pd.read_csv(
    f"{TRAIN_PATH}/train_ground_truth.tsv",
    sep="\t"
)

In [11]:
print("Source 1:", s1.shape)
print("Source 2:", s2.shape)
print("Source 3:", s3.shape)
print("Ground Truth:", ground_truth.shape)

Source 1: (2206821, 4)
Source 2: (5034616, 4)
Source 3: (5285603, 4)
Ground Truth: (2206821, 2)

In [13]:
# Basic structure
print("S1 columns:", s1.columns.tolist())
print("S2 columns:", s2.columns.tolist())
print("S3 columns:", s3.columns.tolist())
print("GT columns:", ground_truth.columns.tolist())

S1 columns: ['entity_id', 'business_name', 'business_address', 'country']
S2 columns: ['entity_id', 'business_name', 'business_address', 'country']
S3 columns: ['entity_id', 'business_name', 'business_address', 'country']
GT columns: ['source1_entity_id', 'matched_entity_ids']

In [12]:
display(s1.head())
display(s2.head())
display(s3.head())
display(ground_truth.head())

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [14]:
print("S1 missing values:")
display(s1.isna().sum())

print("S2 missing values:")
display(s2.isna().sum())

print("S3 missing values:")
display(s3.isna().sum())

S1 missing values:

entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

S2 missing values:

entity_id                0
business_name            2
business_address    168967
country                  0
dtype: int64

S3 missing values:

entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64

In [15]:
print("S1:")
print(s1.dtypes)

print("\nS2:")
print(s2.dtypes)

print("\nS3:")
print(s3.dtypes)

S1:
entity_id           object
business_name       object
business_address    object
country             object
dtype: object

S2:
entity_id           object
business_name       object
business_address    object
country             object
dtype: object

S3:
entity_id           object
business_name       object
business_address    object
country             object
dtype: object

In [16]:
def memory_usage_mb(df):
    return df.memory_usage(deep=True).sum() / (1024 ** 2)

print(f"S1 memory: {memory_usage_mb(s1):.2f} MB")
print(f"S2 memory: {memory_usage_mb(s2):.2f} MB")
print(f"S3 memory: {memory_usage_mb(s3):.2f} MB")
print(f"GT memory: {memory_usage_mb(ground_truth):.2f} MB")

S1 memory: 604.43 MB
S2 memory: 1418.80 MB
S3 memory: 1478.47 MB
GT memory: 321.17 MB

In [17]:
import os
import psutil

ram = psutil.virtual_memory()

print(f"Total RAM: {ram.total / 1024**3:.2f} GB")
print(f"Available RAM: {ram.available / 1024**3:.2f} GB")

Total RAM: 47.05 GB
Available RAM: 41.32 GB

In [18]:
gt = ground_truth.copy()

gt["num_matches"] = (
    gt["matched_entity_ids"]
    .fillna("")
    .astype(str)
    .apply(lambda x: 0 if x.strip() == "" else len(x.split(",")))
)

print(gt["num_matches"].describe())

print("\nMatch count distribution:")
display(
    gt["num_matches"]
    .value_counts()
    .sort_index()
    .head(30)
)

count    2.206821e+06
mean     3.461253e+00
std      1.705323e+00
min      0.000000e+00
25%      2.000000e+00
50%      3.000000e+00
75%      5.000000e+00
max      1.100000e+01
Name: num_matches, dtype: float64

Match count distribution:

num_matches
0     123247
1     119157
2     375212
3     530841
4     484115
5     321957
6     164868
7      63968
8      18680
9       4205
10       534
11        37
Name: count, dtype: int64

In [19]:
print("Singletons:", (gt["num_matches"] == 0).sum())
print("With >=1 match:", (gt["num_matches"] > 0).sum())
print("With multiple matches:", (gt["num_matches"] > 1).sum())

Singletons: 123247
With >=1 match: 2083574
With multiple matches: 1964417

In [20]:
pd.set_option("display.max_colwidth", 150)

display(
    s1[
        ["entity_id", "business_name", "business_address", "country"]
    ].sample(20, random_state=42)
)

,entity_id,business_name,business_address,country
2195840,S1-53356671,Pediatric Medicine PLLC,"4850 20, Otisco, NY",US
1487051,S1-320151505,Fetech National Twin,"19034 Woodburn Road, Woodburn, IN",US
1878277,S1-938947364,General Design Innovations LLC,"7241 Osage Avenue, Mesa, AZ",US
993966,S1-195839862,Construction Ideaz Papers Private Limited,"Building No.4/606, Prabhul Cottage Karimbalur, Elakamon, Ayiroor P.O., Thiruvananthapuram, Trivandrum, Kerala",India
565428,S1-655046555,Penaloza and Bittle First Inc.,"4255 Charleswood Avenue, Memphis, TN",US
1645753,S1-758070915,National Investments LLC,"1641 Virginia Lane, Hueytown, AL",US
1165724,S1-169338169,Reus Idaho Company,"Sanford, ME, 31 Guillemette Street",US
363842,S1-796421498,Creative Projects Limited,"12Thfloor, C, 1204, Roya Oasis, Jankalyan Nagarmalvani, Nr Billabong School, Malad W, Mumbai, Mumbai City, Maharashtra",India
962445,S1-802535179,Goar Stone LLC,"2105 Wood Ridge Cove, Cedar Park, TX",US
964820,S1-97176033,Lakshmi Consultants Private Limited,"A-301, New Sai Dham Chsl, Ramdev Park Road, Thane, Maharashtra",India
1416829,S1-983540069,Ss Technology Private Limited,"Shop No. 1164, Pvt No.2, First Floor Kucha Mahajani, Chandni Chowk, Delhi, Central Delhi, Delhi",India
1333566,S1-642488269,Rebbecca's Family Practice,"2514 Messick Drive, Goshen, IN",US
759621,S1-426953208,Heritage Society LLC,"139 Fort Graham Road, Whitney, TX",US
281676,S1-818320211,Rozy Media Limited,"Survey Number 127/P1, Opp, 66 Kv Ss, Varetha, Mahesana, Kheralu, Mahesana, Gujarat",India
1689696,S1-33984562,Slate PLLC,"735 Charlton Street, Southbridge, MA",US
1581422,S1-709960468,Apex Center,"4 Hillside Court, Coxsackie, NY",US
534257,S1-986840295,M 9 Certified Giant LLC,"4122 Scenic Drive, Dickinson, TX",US
631849,S1-836296604,Coromandal Marketing Private Limited,"G-3, Neel Madhav, Valji Ladha Cross Road, Near Hiera Mongi Hospital, Mulund (W), Mumbai, Maharashtra",India
531606,S1-975412735,Preferred Business Systems Inc,"Loudoun County, 23355 Florina Court, VA",US
100036,S1-739708548,Dream Investment Pvt Ltd,"2A, 2Nd Floor, Windcliffe, 50 D Peddar Road, Cumballa Hill, Mumbai, Mumbai City, Maharashtra",India

In [21]:
display(
    s2[
        ["entity_id", "business_name", "business_address", "country"]
    ].sample(20, random_state=42)
)

,entity_id,business_name,business_address,country
2641297,S2-61703745,Harbor Center,"6309 EVANGELINE TRAIL, AUSTIN, TX",US
1856454,S2-420680068,STEWARD ACE PREMIER,"1029 MAPLE HILL RD, LEBANON, TN",US
371269,S2-190917211,Klapper and Lott,"368 VINE STREET, TOOELE, UT",US
793182,S2-109564077,EAR NOSE & THROAT CARE,"YORK RD, LUTHERVILLE, MD",US
4159519,S2-483058783,Shield Inrfabuild Private Limited,"206 FLAT NO. LG 1 KH NO. 514, 516 SHYAM BHAWAN JHANDA COLONY FATEHPUR, DELHI, Delhi",India
2290871,S2-257746699,#holtline,"HOUSTON, 6119 DARLINGHURST DRIVE, TX",US
2479261,S2-476138086,Cancer [Services],NaN,US
606462,S2-420894180,Smt Hermes Private Limited Center,"Delhi, HOUSE NO 138, 2ND FLOOR, BLK C, PKT 2 DDA MARKET, SECTOR 16, ROHINI, DELHI",India
3805434,S2-498993768,AMARDEEP PTER PRIVATE LIMITED,"332NEAR TELCO SERVICE STATION RANGPURI, NEW DELHI, Delhi",India
2960649,S2-54193377,Impex-+-Brothers,"FLAT B 1801, PL-15&17, SECTOR 7, PATEL HERITAGE, KHARGHAR, NAVI MUMBAI, महाराष्ट्र",India
798381,S2-721297669,Anderson & Barney Patriot Corp,"218 19TH TER, KANSAS CITY, MO",US
2616927,S2-299697282,Halkos Blockchain Inc,"3154-3158 PETERKIN AVENUE, ANCHOARGE, AK",US
166846,S2-273907271,Oyola Líberty Harmony Associates,"601 SPRUCE STREET, IOLA, KS",US
4235460,S2-595122948,ग्रेट टेक केयर प्रा. लि.,"C/O. BABU YALLAPPA WADAR, A/P- KUDNUR, TAL CHANDGAD, KOLHAPUR, CHANDGAD, Maharashtra",India
3755200,S2-472836160,HEALTH AALMLCE,"2975 1/2 GLENMARE ST, SALT LAKE CITY, UT",US
4149972,S2-550687702,Indorama Inn (India) Ltd,"GROUND FLOOR, BEARING NO.0102, IN POCKET-15, ROHINI SECTOR-22, DELHI, null, दिल्ली",India
406749,S2-337429097,HODZIC FASHION SERVICES,"1507 BELL STREET, GREENACRES CITY, WA",US
1052954,S2-163014489,Sri PATERSON GROUP,"NO. 208 B 2/101B FIRST FLOOR, SAFDARJUNG ENCLAVE, NEW DELHI, Delhi",India
1307092,S2-473939517,TECH PRIVATE FINANCIAL VENTURES TIRUPATI LIMITED,"87 MUTHOOT CENTRE, TC NO 27/ 3022 PUNNEN ROAD, THIRUVANANTHAPURAM, THIRUVANANTHAPURAM, Kerala",India
2302065,S2-105896641,Signature Wealth Works Partners,"235 SHANNON ST, TAZEWELL TOWN, VA",US

In [22]:
display(
    s3[
        ["entity_id", "business_name", "business_address", "country"]
    ].sample(20, random_state=42)
)

,entity_id,business_name,business_address,country
726818,S3-239979459,Dr Apex Pvt Ltd Partners,"75 Tulshibaugwale Colonysahakarnagar, Pune, MH",India
1045360,S3-109491785,Shiva Mines Pvt Ltd,"F-17, Sector 22, Noida, Gautam Buddha Nagar, उत्तर प्रदेश",India
4785624,S3-586835953,Vanguard Métropolitan Sunshine,"3518-B Crestview Ln, Catoosa, Oklahoma",US
2503843,S3-449000694,Vanguard Apoge-Inc,"2150 350, Greencastle, Indiana",US
3149825,S3-397034729,रियल एग्रो प्राइवेट लिमिटेड,"H.no 829 D-225vivek Vihar, Delhi, दिल्ली",India
2749542,S3-553748449,Irinovi,"324 Laramie Ave, Chicago, Illinois",US
3399114,S3-787185173,Jarleon Worldwide Llc,"353 Spruce Pine Road, Abingdon, Maryland",US
1611580,S3-691178620,Sfoasseeg L.L.C.,"1161d Brookside Ave, Evansdale, Iowa",US
3556867,S3-138902486,Brixhalo t/a Creative Enterprises,"6, Madurai Road, Trichy, Tamil Nadu",India
4340188,S3-568450939,Nachiket Solutions Limited,"138 / 6, Kiran Complex Zone - Ii, M. P. Nagar Bhopal, Bhopal, मध्य प्रदेश",India
50977,S3-468440022,Tolbert Pacific Southern,"476 475, Bloomfield, Indiana",US
260503,S3-451416708,New Dhei Products LLP,"North Delhi, New Delhi, 13 A Kamla Nagar, DL",India
3874421,S3-569241237,"Primary Care Associates,","6175 Twentieth Street, Rockford, Illinois",US
1737861,S3-976491069,Mavis Mincey Optimal-Tungsten,NaN,US
2304682,S3-475009787,Valueanalytics.Com,"Kansa CITY CITY, Missouri, Jackson Avenue",US
4989395,S3-69807298,Clear Clear Inc Medical,"889 Morning Star Ct, Mason City, Iowa",US
1109096,S3-451600706,Sidhartha Kaka,"Kh.no. 31/5/1 And 2 Groud Floor, Village Salempur Majra Blk-h Street No 5 Uttrakhand Enclave, North Delhi, DL",India
4633301,S3-347097728,Vision Center,"5 Palmer Street, # B, Athens, Ohio",US
5064219,S3-764848577,Ashoka-+ Brothers Private Ltd,"Trivandrum, Tc-16/1776/5, Thiruvananthapuram, KL",India
2310567,S3-881407444,Martin Inc Services,"104 Woodland Drive, Richmond, Kentucky",US

In [24]:
# --------------------------------------------------
# 1. Check actual data types
# --------------------------------------------------

print("S1 dtypes")
display(s1.dtypes)

print("\nS2 dtypes")
display(s2.dtypes)

print("\nS3 dtypes")
display(s3.dtypes)


# --------------------------------------------------
# 2. Ground-truth match count
# --------------------------------------------------

gt_analysis = ground_truth.copy()

gt_analysis["matched_entity_ids"] = (
    gt_analysis["matched_entity_ids"]
    .fillna("")
    .astype(str)
)

gt_analysis["num_matches"] = gt_analysis["matched_entity_ids"].apply(
    lambda x: 0 if x.strip() == "" else len(x.split(","))
)

print("\nMatch-count statistics:")
display(gt_analysis["num_matches"].describe())

print("\nMatch-count distribution:")
display(
    gt_analysis["num_matches"]
    .value_counts()
    .sort_index()
    .head(30)
)

print(
    "\nSingleton S1 entities:",
    (gt_analysis["num_matches"] == 0).sum()
)

print(
    "S1 entities with at least one match:",
    (gt_analysis["num_matches"] > 0).sum()
)

print(
    "S1 entities with multiple matches:",
    (gt_analysis["num_matches"] > 1).sum()
)


# --------------------------------------------------
# 3. Look at actual examples
# --------------------------------------------------

pd.set_option("display.max_colwidth", 150)

print("\nSource 1 examples")
display(s1.sample(10, random_state=42))

print("\nSource 2 examples")
display(s2.sample(10, random_state=42))

print("\nSource 3 examples")
display(s3.sample(10, random_state=42))


# --------------------------------------------------
# 4. Memory usage
# --------------------------------------------------

def memory_mb(df):
    return df.memory_usage(deep=True).sum() / 1024**2

print("\nMemory:")
print(f"S1: {memory_mb(s1):.2f} MB")
print(f"S2: {memory_mb(s2):.2f} MB")
print(f"S3: {memory_mb(s3):.2f} MB")
print(f"GT: {memory_mb(ground_truth):.2f} MB")

S1 dtypes

entity_id           object
business_name       object
business_address    object
country             object
dtype: object

S2 dtypes

entity_id           object
business_name       object
business_address    object
country             object
dtype: object

S3 dtypes

entity_id           object
business_name       object
business_address    object
country             object
dtype: object

Match-count statistics:

count    2.206821e+06
mean     3.461253e+00
std      1.705323e+00
min      0.000000e+00
25%      2.000000e+00
50%      3.000000e+00
75%      5.000000e+00
max      1.100000e+01
Name: num_matches, dtype: float64

Match-count distribution:

num_matches
0     123247
1     119157
2     375212
3     530841
4     484115
5     321957
6     164868
7      63968
8      18680
9       4205
10       534
11        37
Name: count, dtype: int64

Singleton S1 entities: 123247
S1 entities with at least one match: 2083574
S1 entities with multiple matches: 1964417

Source 1 examples

,entity_id,business_name,business_address,country
2195840,S1-53356671,Pediatric Medicine PLLC,"4850 20, Otisco, NY",US
1487051,S1-320151505,Fetech National Twin,"19034 Woodburn Road, Woodburn, IN",US
1878277,S1-938947364,General Design Innovations LLC,"7241 Osage Avenue, Mesa, AZ",US
993966,S1-195839862,Construction Ideaz Papers Private Limited,"Building No.4/606, Prabhul Cottage Karimbalur, Elakamon, Ayiroor P.O., Thiruvananthapuram, Trivandrum, Kerala",India
565428,S1-655046555,Penaloza and Bittle First Inc.,"4255 Charleswood Avenue, Memphis, TN",US
1645753,S1-758070915,National Investments LLC,"1641 Virginia Lane, Hueytown, AL",US
1165724,S1-169338169,Reus Idaho Company,"Sanford, ME, 31 Guillemette Street",US
363842,S1-796421498,Creative Projects Limited,"12Thfloor, C, 1204, Roya Oasis, Jankalyan Nagarmalvani, Nr Billabong School, Malad W, Mumbai, Mumbai City, Maharashtra",India
962445,S1-802535179,Goar Stone LLC,"2105 Wood Ridge Cove, Cedar Park, TX",US
964820,S1-97176033,Lakshmi Consultants Private Limited,"A-301, New Sai Dham Chsl, Ramdev Park Road, Thane, Maharashtra",India

Source 2 examples

,entity_id,business_name,business_address,country
2641297,S2-61703745,Harbor Center,"6309 EVANGELINE TRAIL, AUSTIN, TX",US
1856454,S2-420680068,STEWARD ACE PREMIER,"1029 MAPLE HILL RD, LEBANON, TN",US
371269,S2-190917211,Klapper and Lott,"368 VINE STREET, TOOELE, UT",US
793182,S2-109564077,EAR NOSE & THROAT CARE,"YORK RD, LUTHERVILLE, MD",US
4159519,S2-483058783,Shield Inrfabuild Private Limited,"206 FLAT NO. LG 1 KH NO. 514, 516 SHYAM BHAWAN JHANDA COLONY FATEHPUR, DELHI, Delhi",India
2290871,S2-257746699,#holtline,"HOUSTON, 6119 DARLINGHURST DRIVE, TX",US
2479261,S2-476138086,Cancer [Services],NaN,US
606462,S2-420894180,Smt Hermes Private Limited Center,"Delhi, HOUSE NO 138, 2ND FLOOR, BLK C, PKT 2 DDA MARKET, SECTOR 16, ROHINI, DELHI",India
3805434,S2-498993768,AMARDEEP PTER PRIVATE LIMITED,"332NEAR TELCO SERVICE STATION RANGPURI, NEW DELHI, Delhi",India
2960649,S2-54193377,Impex-+-Brothers,"FLAT B 1801, PL-15&17, SECTOR 7, PATEL HERITAGE, KHARGHAR, NAVI MUMBAI, महाराष्ट्र",India

Source 3 examples

,entity_id,business_name,business_address,country
726818,S3-239979459,Dr Apex Pvt Ltd Partners,"75 Tulshibaugwale Colonysahakarnagar, Pune, MH",India
1045360,S3-109491785,Shiva Mines Pvt Ltd,"F-17, Sector 22, Noida, Gautam Buddha Nagar, उत्तर प्रदेश",India
4785624,S3-586835953,Vanguard Métropolitan Sunshine,"3518-B Crestview Ln, Catoosa, Oklahoma",US
2503843,S3-449000694,Vanguard Apoge-Inc,"2150 350, Greencastle, Indiana",US
3149825,S3-397034729,रियल एग्रो प्राइवेट लिमिटेड,"H.no 829 D-225vivek Vihar, Delhi, दिल्ली",India
2749542,S3-553748449,Irinovi,"324 Laramie Ave, Chicago, Illinois",US
3399114,S3-787185173,Jarleon Worldwide Llc,"353 Spruce Pine Road, Abingdon, Maryland",US
1611580,S3-691178620,Sfoasseeg L.L.C.,"1161d Brookside Ave, Evansdale, Iowa",US
3556867,S3-138902486,Brixhalo t/a Creative Enterprises,"6, Madurai Road, Trichy, Tamil Nadu",India
4340188,S3-568450939,Nachiket Solutions Limited,"138 / 6, Kiran Complex Zone - Ii, M. P. Nagar Bhopal, Bhopal, मध्य प्रदेश",India

Memory:
S1: 604.43 MB
S2: 1418.80 MB
S3: 1478.47 MB
GT: 321.17 MB

In [25]:
import pandas as pd

# ---------------------------------------------------------
# Select some S1 entities with different match counts
# ---------------------------------------------------------

samples = []

for count, n, seed in [
    (0, 5, 10),   # singleton / no match
    (1, 5, 20),   # exactly one match
    (3, 5, 30),   # three matches
    (7, 5, 40),   # many matches
]:
    ids = (
        gt_analysis.loc[
            gt_analysis["num_matches"] == count,
            "source1_entity_id"
        ]
        .sample(n=min(n, (gt_analysis["num_matches"] == count).sum()),
                random_state=seed)
        .tolist()
    )
    samples.extend(ids)

# ---------------------------------------------------------
# Ground-truth rows for selected S1 entities
# ---------------------------------------------------------

sample_gt = ground_truth[
    ground_truth["source1_entity_id"].isin(samples)
].copy()

# ---------------------------------------------------------
# Collect all matched S2/S3 IDs
# ---------------------------------------------------------

s2_ids = set()
s3_ids = set()

for _, row in sample_gt.iterrows():
    matched = str(row["matched_entity_ids"])

    if matched == "" or matched == "nan":
        continue

    for entity_id in matched.split(","):
        entity_id = entity_id.strip()

        if entity_id.startswith("S2-"):
            s2_ids.add(entity_id)

        elif entity_id.startswith("S3-"):
            s3_ids.add(entity_id)

# ---------------------------------------------------------
# Fetch only these records from the huge datasets
# ---------------------------------------------------------

sample_s1 = s1[
    s1["entity_id"].isin(samples)
].copy()

sample_s2 = s2[
    s2["entity_id"].isin(s2_ids)
].copy()

sample_s3 = s3[
    s3["entity_id"].isin(s3_ids)
].copy()

# ---------------------------------------------------------
# Display
# ---------------------------------------------------------

for _, row in sample_gt.iterrows():

    s1_id = row["source1_entity_id"]
    matches = str(row["matched_entity_ids"])

    print("=" * 100)
    print("S1:", s1_id)
    print("Ground Truth:", matches)

    print("\nSOURCE 1")
    display(
        sample_s1[
            sample_s1["entity_id"] == s1_id
        ]
    )

    matched_ids = []

    if matches != "" and matches != "nan":
        matched_ids = [
            x.strip() for x in matches.split(",")
        ]

    if matched_ids:
        print("\nMATCHED SOURCE 2")
        display(
            sample_s2[
                sample_s2["entity_id"].isin(matched_ids)
            ]
        )

        print("\nMATCHED SOURCE 3")
        display(
            sample_s3[
                sample_s3["entity_id"].isin(matched_ids)
            ]
        )

====================================================================================================
S1: S1-386788200
Ground Truth: S2-960033213,S3-108524099,S3-235440061

SOURCE 1

,entity_id,business_name,business_address,country
1114912,S1-386788200,Belindyne International Inc,"1463 New Deal Potts Road, Portland, TN",US

MATCHED SOURCE 2

,entity_id,business_name,business_address,country
2716680,S2-960033213,belindyneinternational.com,"1463 New Deal Potts Road, PORTLAND, TN",US

MATCHED SOURCE 3

,entity_id,business_name,business_address,country
1804430,S3-108524099,Belindyne Inc Partners,"463 New Deal Potts Road, Portland, Tennessee",US
4743867,S3-235440061,Belindyne International,"Tennessee, Portland, 463 New Deal Potts Road",US

====================================================================================================
S1: S1-52628215
Ground Truth: S2-994212252,S2-209360836,S3-813384345,S3-355681390,S3-781292588,S3-428834513,S3-630335198

SOURCE 1

,entity_id,business_name,business_address,country
22176,S1-52628215,Axis Innovation Private Limited,"B-298, Plot No. 12-B, G/F Block B New Ashok Nagar, Delhi, East Delhi, Delhi",India

MATCHED SOURCE 2

,entity_id,business_name,business_address,country
2928280,S2-994212252,AXIS AXIS INNOVATION PRIVATE,"B-298, PLOT NO. 12-B, G/F BLOCK B NEW ASHOK NAGAR, DELHI, दिल्ली",India
5030621,S2-209360836,Private Axis Innovation Ltd,"B-298, DILSHAD GARDEN, Delhi",India

MATCHED SOURCE 3

,entity_id,business_name,business_address,country
372053,S3-813384345,M/s Axis Innovation Private Limited,"B-298, Delhi, East Delhi, DL",India
2196497,S3-355681390,innovationaxis.com,"B-298, East Delhi, Delhi, DL",India
3286995,S3-781292588,AXIS INNOVATION PRIVATE LIMITED,"B-298, Delhi, DL",India
3767327,S3-428834513,Axis-Innovation Private Limited,"B-298, East Delhi, दिल्ली",India
4387512,S3-630335198,Ectovera f/k/a Axis Innovation Private Limited,"B-298, Plot No. 12-B, G/F Block B New Ashok Nagar, Delhi, East Delhi, Delhi",India

====================================================================================================
S1: S1-816190896
Ground Truth: S2-533165131

SOURCE 1

,entity_id,business_name,business_address,country
161187,S1-816190896,Key Agriculture (India) Private Limited,"9-228 Bc Colony, Near Panchayathi Office, Nekarikallu, Guntur, Andhra Pradesh",India

MATCHED SOURCE 2

,entity_id,business_name,business_address,country
3050239,S2-533165131,PRIVATE KEY AGRICULTURE (INDIA) LIMITED,"H.NO 9-228 BC COLONY, NEAR PANCHAYATHI OFFICE, GUNTUR, NEKARIKALLU, ఆంధ్రప్రదేశ్",India

MATCHED SOURCE 3

Empty DataFrame
Columns: [entity_id, business_name, business_address, country]
Index: []

====================================================================================================
S1: S1-658352233
Ground Truth: S2-431298990

SOURCE 1

,entity_id,business_name,business_address,country
1122157,S1-658352233,Design (India) Internet Private Limited,"Sc0 8, C-Block Ranjit Avenue, Amritsar, Punjab",India

MATCHED SOURCE 2

,entity_id,business_name,business_address,country
1185029,S2-431298990,Design (India) Internet Private,"SC0 8, C-BLOCK RANJIT AVENUE, AMRITSAR, Punjab",India

MATCHED SOURCE 3

Empty DataFrame
Columns: [entity_id, business_name, business_address, country]
Index: []

====================================================================================================
S1: S1-268909399
Ground Truth: S2-120652478,S3-923252401,S3-147437763

SOURCE 1

,entity_id,business_name,business_address,country
1783394,S1-268909399,Tradewell Dot Private Limited,"Flat 705 Login Cts No 886, Pt, Bhander Pakhadi Road, Kandivali West, Mumbai, Maharashtra",India

MATCHED SOURCE 2

,entity_id,business_name,business_address,country
3793813,S2-120652478,Tradewell Dot Prívate Limited,"FLAT #705 LOGIN CTS NO 886, PT, BHANDER PAKHADI ROAD, KANDIVALI WEST, Maharashtra",India

MATCHED SOURCE 3

,entity_id,business_name,business_address,country
3480584,S3-147437763,Tradewell Dot Private Limited,"Mumbai Suburban, Flat 705 Login Cts No 886, MH",India
4542709,S3-923252401,tradewell dot private limited,"Churu, Flat 705 Login Cts No 886, MH",India

====================================================================================================
S1: S1-72395414
Ground Truth: S2-568685455,S2-4950077,S2-356249442,S2-911528877,S2-200995387,S3-302523151,S3-132404706

SOURCE 1

,entity_id,business_name,business_address,country
731179,S1-72395414,Red Seafood,"273 Cambridge Road, Unit 206, Woburn, MA",US

MATCHED SOURCE 2

,entity_id,business_name,business_address,country
238814,S2-200995387,RED SEAFOOD CO,"273 CAMBRIDGE RD, WOBURN, MA",US
500500,S2-4950077,RED-(SEAFOOD),"273 CAMBRIDGE ROAD, WOBURN, MA",US
2524147,S2-911528877,RED SEAFOOD CENTER,"MA, 273 CAMBRIDGE ROAD, WOBURN",US
3286174,S2-568685455,Red Seafood,"273 CAMBRIDGE RD, WOBURN, MA",US
4068579,S2-356249442,Red Seafood,"273 CAMBRIDGE RD, MA, WOBURN",US

MATCHED SOURCE 3

,entity_id,business_name,business_address,country
133314,S3-132404706,Red Seafood Co,"Woburn, 273 Cambridge Rd, Massachusetts",US
1931267,S3-302523151,rédseaf0od.com,"273 Cambridge Rd, Unit 206, Woburn, Massachusetts",US

====================================================================================================
S1: S1-727547583
Ground Truth: S2-572993467,S3-718215621,S3-221045412

SOURCE 1

,entity_id,business_name,business_address,country
1309915,S1-727547583,Best Engineering Pvt Ltd,"Pln167, Wn136, Veer Hanuman, Mandir Chikhalicha Raja, Nagpur, Maharashtra",India

MATCHED SOURCE 2

,entity_id,business_name,business_address,country
2827633,S2-572993467,बेस्ट इंजीनियरिंग प्रा. लि.,"PLN169, WN136, VEER HANUMAN, MANDIR CHIKHALICHA RAJA, NAGPUR, महाराष्ट्र",India

MATCHED SOURCE 3

,entity_id,business_name,business_address,country
1778328,S3-221045412,बेस्ट इंजीनियरिंग प्रा. लि.,"Pln#167, Nagpur, MH",India
4324336,S3-718215621,best engineering pvt ltd,"Pln#167, MH, Nagpur",India

====================================================================================================
S1: S1-913350352
Ground Truth: nan

SOURCE 1

,entity_id,business_name,business_address,country
2163765,S1-913350352,Wilson Assets Inc.,"9428 Pavo Lane, City Of El Paso, TX",US

====================================================================================================
S1: S1-227528931
Ground Truth: nan

SOURCE 1

            entity_id            business_name      business_address country
1709931  S1-227528931  Apex Star Portfolio LLC  1315 455, Sparta, KY      US

====================================================================================================
S1: S1-812784066
Ground Truth: S3-924248167

SOURCE 1

           entity_id         business_name            business_address country
274480  S1-812784066  Maex Holding Company  930 Main Street, Genoa, IL      US

MATCHED SOURCE 2

Empty DataFrame
Columns: [entity_id, business_name, business_address, country]
Index: []

MATCHED SOURCE 3

            entity_id  business_name                  business_address country
3863489  S3-924248167  Maex  Holding  930 Main Street, Genoa, Illinois      US

====================================================================================================
S1: S1-14278857
Ground Truth: S2-611190697,S2-496496078,S3-465107518

SOURCE 1

,entity_id,business_name,business_address,country
1943570,S1-14278857,Fortune Foods Private Limited,"688/A-3 Shalimar Gdn, Extension I, Ghaziabad, Uttar Pradesh",India

MATCHED SOURCE 2

,entity_id,business_name,business_address,country
2953137,S2-496496078,फॉर्च्यून फूड्स प्राइवेट लिमिटेड,"#688/A-3 SHALIMAR GDN, EXTENSION I, GHAZIABAD, Uttar Pradesh",India
3686852,S2-611190697,फॉर्च्यून फूड्स प्राइवेट लिमिटेड,"688/A-3 SHALIMAR GDN, EXTENSION I, GHAZIABAD, Uttar Pradesh",India

MATCHED SOURCE 3

,entity_id,business_name,business_address,country
3488674,S3-465107518,Fortune Fds Private Limited,"Door No 688/A-3 Shalimar Gdn, Ghaziabad, UP",India

====================================================================================================
S1: S1-491534716
Ground Truth: nan

SOURCE 1

,entity_id,business_name,business_address,country
1855568,S1-491534716,HXO Domain Private Limited,"Plot No. D-2-Ch-360 & 361, Gujarat, Bharuch, Dahej Ii",India

====================================================================================================
S1: S1-334871731
Ground Truth: S2-704727760

SOURCE 1

,entity_id,business_name,business_address,country
261986,S1-334871731,Anjalee & Brothers Private Limited,"B-95, Shivalik Colony Malviya Nagar, Delhi, South Delhi, Delhi",India

MATCHED SOURCE 2

,entity_id,business_name,business_address,country
4855656,S2-704727760,Anjalee + Brothers Private Limited,"B-95, SHIVALIK COLONY MALVIYA NAGAR, DELHI, Delhi",India

MATCHED SOURCE 3

Empty DataFrame
Columns: [entity_id, business_name, business_address, country]
Index: []

====================================================================================================
S1: S1-917288584
Ground Truth: S2-780649591,S2-695127520,S3-954061833,S3-415208818,S3-960368165,S3-234529146,S3-880115039

SOURCE 1

,entity_id,business_name,business_address,country
374112,S1-917288584,Ivenium Urban L.L.C.,"Albuquerque, NM, 6801 Dragonfly Lane",US

MATCHED SOURCE 2

,entity_id,business_name,business_address,country
8030,S2-695127520,Ivenium Urban L.L.C.,"NM, 006801 Dragonfly Lane, ALBUQUERQUE",US
3668108,S2-780649591,Ivenium Urban,"006801 DRAGONFLY LANE, ALBUQUERQUE, NM",US

MATCHED SOURCE 3

,entity_id,business_name,business_address,country
162455,S3-960368165,lvenium Urban L.L.C.,"6801 Dragonfly Lane, Albuquerque, New Mexico",US
778223,S3-880115039,Ivenium L.L.C. Center,NaN,US
3492546,S3-954061833,The The Ivenium Urban L.L.C.,"6801 Dragonfly Lane, Albuquerque, New Mexico",US
3801717,S3-415208818,Ivenium-Urban,"6801 Dragonfly Lane, Albuquerque, New Mexico",US
4889936,S3-234529146,Ivenium úrban L.L.C.,NaN,US

====================================================================================================
S1: S1-459017314
Ground Truth: S2-218289639,S2-670491495,S2-257219252,S2-601211034,S3-101234544,S3-28791922,S3-412515275

SOURCE 1

,entity_id,business_name,business_address,country
352327,S1-459017314,Indo Engineering Pvt Ltd,"Hanuman Chowk, Gola Road, Near Dr. Dukhan Ram D.A.V. School, Ward No. 20, P.S.- Danapur, Dinapur-Cum-Khagaul, Patna, Bihar",India

MATCHED SOURCE 2

,entity_id,business_name,business_address,country
1274256,S2-257219252,Indo Engineering Pvt Limited,"बिहार, HANUMAN CHOWK, GOLA ROAD, NEAR DR. DUKHAN RAM D.A.V. SCHOOL, WARD NO. 20, P.S.- DANAPUR, DINAPUR-CUM-KHAGAUL",India
1525784,S2-670491495,Indo इंजीनियरिंग प्रा. लि.,"HANUMAN CHOW, GOLA ROAD, NEAR DR. DUKHAN RAM D.A.V. SCHOOL, WARD NO. 20, P.S.- DANAPUR, DINAPUR-CUM-KHAGAUL, Bihar",India
2998857,S2-601211034,इंडो इंजीनियरिंग प्रा. लि.,"HANUMAN CHOWK, GOLA ROAD, NEAR DR. DUKHAN RAM D.A.V. SCHOOL, WARD NO. 20, P.S.- DANAPUR, Bihar, PATNA, DINAPUR-CUM-KHAGAUL",India
3459790,S2-218289639,Indo Engineering Pvt Pvt,"HANUMAN CHOWK, GOLA ROAD, NEAR DR. DUKHAN RAM D.A.V. SCHOOL, WARD NO. 20, P.S.- DANAPUR, DINAPUR-CUM-KHAGAUL, बिहार",India

MATCHED SOURCE 3

,entity_id,business_name,business_address,country
424464,S3-28791922,इंडो इंजीनियरिंग प्रा. लि.,"Hanuman Chowk, Gola Road, Near Dr. Dukhan Ram D.a.v. School, Ward No. 20, P.s.- Danapur, Patna, Dinapur-cum-khagaul, BR",India
2968417,S3-101234544,Indo Engineering Pvt Limited,"Hanuman Chowk, Gola Road, Near Dr. Dukhan Ram D.a.v. School, Ward No. 20, P.s.- Danapur, Dinapur-cum-khagaul, Patna, बिहार",India
4082258,S3-412515275,INDO ENGINEERING PVT LTD,"Dinapur-cum-khagaul, Hanuman Chowk, BR, Patna, Gola Road, Near Dr. Dukhan Ram D.a.v. School, Ward No. 20, P.s.- Danapur",India

====================================================================================================
S1: S1-401042897
Ground Truth: nan

SOURCE 1

,entity_id,business_name,business_address,country
979607,S1-401042897,Solvex Food Private Limited,"Salem, Tamil Nadu, Salem, Pethan Valavu, Sauriyur Po Jalakandapuram, No.13/6",India

====================================================================================================
S1: S1-390116856
Ground Truth: S2-800579524,S2-216649466,S2-227931090,S3-656510360,S3-913128619,S3-328815961,S3-713594211

SOURCE 1

            entity_id business_name                business_address country
1807335  S1-390116856    Traix PLLC  2218 Janes Lane, Covington, KY      US

MATCHED SOURCE 2

,entity_id,business_name,business_address,country
492365,S2-227931090,PLLC Traix,"2218 JANES LN, COVINGTON, KY",US
2875597,S2-216649466,Traix PLLC,"2218 JANES LN, COVINGTON KY, KY",US
3282308,S2-800579524,Vantagedrexriza,"JANES LANE, COVINGTON KY, KY",US

MATCHED SOURCE 3

,entity_id,business_name,business_address,country
1449459,S3-913128619,Traix Pllc,"2218 Janes Lane, NULL, Covington, Kentucky",US
2334501,S3-713594211,Tcndaxi PLLC (ID: 49668),"2218 Janes Ln, NULL, Covington Ky, Kentucky",US
3507079,S3-656510360,Traix PLLC,"2218 Janes Lane, NULL, Covington, Kentucky",US
4869408,S3-328815961,Tcgix PLLC,"Covington Ky, 2218 Janes Ln, NULL, Kentucky",US

====================================================================================================
S1: S1-328492652
Ground Truth: S3-250864826

SOURCE 1

,entity_id,business_name,business_address,country
332228,S1-328492652,Krishna Technology Private Limited,"Chhijjarsi Colony, Noida, Gautam Buddha Nagar, Uttar Pradesh",India

MATCHED SOURCE 2

Empty DataFrame
Columns: [entity_id, business_name, business_address, country]
Index: []

MATCHED SOURCE 3

,entity_id,business_name,business_address,country
911719,S3-250864826,कृष्ण टेक्नोलॉजी प्राइवेट लिमिटेड,"Gautam Buddha Nagar, Noida, Chhijjarsi Colony, UP",India

====================================================================================================
S1: S1-17211335
Ground Truth: nan

SOURCE 1

,entity_id,business_name,business_address,country
716885,S1-17211335,Advanced Arbor Inc,"Wormleysburg Borough, PA, Unit 1, 724 Front Street",US

====================================================================================================
S1: S1-159264032
Ground Truth: S2-605456192,S2-999614450,S3-391728918

SOURCE 1

,entity_id,business_name,business_address,country
1904373,S1-159264032,Future Consultants Limited,"C-2A, Block-C, Old Slum Qtrs, Paschim Puri, New Delhi, West Delhi, Delhi",India

MATCHED SOURCE 2

,entity_id,business_name,business_address,country
2842612,S2-605456192,फ्यूचर कंसल्टेंट्स लिमिटेड,"C-2A, BLOCK-C, OLD SLUM QTRS, PASCHIM PURI, DELHI, NEW DELHI, Delhi",India
4404415,S2-999614450,Future Consultants Ltd,"C-2A, BLOCK-C, OLD SLUM QTRS, PASCHIM PURI, NEW DELHI, Delhi",India

MATCHED SOURCE 3

,entity_id,business_name,business_address,country
2890488,S3-391728918,M/s Future Consultants Limited,"New Delhi, दिल्ली, West Delhi, C-2a, Block-c, Old Slum Qtrs, Paschim Puri",India